//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessHistory
    {
        public int AccessHistory_Id { get; set; }
        public Nullable<bool> AccessHistory_Type { get; set; }
        public Nullable<System.DateTime> AccessHistory_Time { get; set; }
        public Nullable<int> AccessHistory__UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
