//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.DepartmentFieldOperations = new HashSet<DepartmentFieldOperation>();
            this.HistoricalWorks = new HashSet<HistoricalWork>();
            this.Users = new HashSet<User>();
        }
    
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Department_OrganizationId { get; set; }
        public string Department_Information { get; set; }
        public Nullable<int> Department_PhoneNumber { get; set; }
        public Nullable<int> Department_Fax { get; set; }
        public string Department_Email { get; set; }
        public Nullable<bool> Department_Active { get; set; }
        public Nullable<System.DateTime> Department_CreatedOn { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<DepartmentFieldOperation> DepartmentFieldOperations { get; set; }
        public virtual ICollection<HistoricalWork> HistoricalWorks { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
