//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentFieldOperation
    {
        public int DepartmentFieldOperation_Id { get; set; }
        public Nullable<int> DepartmentFieldOperation_DepartmentId { get; set; }
        public Nullable<int> DepartmentFieldOperation_FieldOperationId { get; set; }
        public bool DepartmentFieldOperation_Active { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual FieldOperation FieldOperation { get; set; }
    }
}
