//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int District_Id { get; set; }
        public string District_Name { get; set; }
        public string District_Type { get; set; }
        public string District_Location { get; set; }
        public Nullable<int> District_ProvinceId { get; set; }
        public Nullable<bool> District_Active { get; set; }
    
        public virtual Province Province { get; set; }
    }
}
