//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ethnic
    {
        public Ethnic()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Ethnic_Id { get; set; }
        public string Ethnic_Name { get; set; }
        public bool Ethnic_Active { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
