//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldOperation
    {
        public FieldOperation()
        {
            this.DepartmentFieldOperations = new HashSet<DepartmentFieldOperation>();
            this.UserFieldOperations = new HashSet<UserFieldOperation>();
        }
    
        public int FieldOperation_Id { get; set; }
        public string FieldOperation_Name { get; set; }
        public Nullable<bool> FieldOperation_Active { get; set; }
    
        public virtual ICollection<DepartmentFieldOperation> DepartmentFieldOperations { get; set; }
        public virtual ICollection<UserFieldOperation> UserFieldOperations { get; set; }
    }
}
