//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int Group_Id { get; set; }
        public string Group_Name { get; set; }
        public Nullable<bool> Group_Active { get; set; }
    
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
