//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalWork
    {
        public int HistoricalWork_Id { get; set; }
        public Nullable<int> HistoricalWork_OrganizationId { get; set; }
        public Nullable<int> HistoricalWork_DepartmentId { get; set; }
        public Nullable<int> HistoricalWork_UserId { get; set; }
        public Nullable<int> HistoricalWork_TitleId { get; set; }
        public string HistoricalWork_Type { get; set; }
        public Nullable<System.DateTime> HistoricalWork_EffectFrom { get; set; }
        public Nullable<System.DateTime> HistoricalWork_EffecttTo { get; set; }
        public Nullable<bool> HistoricalWork_Active { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Title Title { get; set; }
        public virtual User User { get; set; }
    }
}
