//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int Opinion_Id { get; set; }
        public Nullable<int> Opinion_From { get; set; }
        public Nullable<int> Opinion_To { get; set; }
        public Nullable<System.DateTime> Opinion_Date { get; set; }
        public Nullable<bool> Opinion_Active { get; set; }
        public string Opinion_Title { get; set; }
        public string Opinion_Content { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
