//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingResult
    {
        public int RatingResult_Id { get; set; }
        public Nullable<int> RatingResult__UserId { get; set; }
        public Nullable<System.DateTime> RatingResult_CreatedOn { get; set; }
        public Nullable<int> RatingResult_RatingId { get; set; }
    
        public virtual Rating Rating { get; set; }
        public virtual User User { get; set; }
    }
}
