//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.RatingResults = new HashSet<RatingResult>();
        }
    
        public int Rating_Id { get; set; }
        public string Rating_Name { get; set; }
        public Nullable<bool> Rating_Active { get; set; }
    
        public virtual ICollection<RatingResult> RatingResults { get; set; }
    }
}
