//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    
    public partial class SOP_GetDetailOrganizationRating_Result1
    {
        public Nullable<int> User_Id { get; set; }
        public string User_FullName { get; set; }
        public string User_UserName { get; set; }
        public int VERYHAPPY { get; set; }
        public int HAPPY { get; set; }
        public int WAITLONG { get; set; }
        public int LOWPROFESSIONAL { get; set; }
        public int BADBEHAVIOR { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
