//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public Title()
        {
            this.HistoricalWorks = new HashSet<HistoricalWork>();
        }
    
        public int Title_Id { get; set; }
        public string Title_Name { get; set; }
        public Nullable<bool> Title_Active { get; set; }
    
        public virtual ICollection<HistoricalWork> HistoricalWorks { get; set; }
    }
}
