//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFieldOperation
    {
        public int UserFieldOperation_Id { get; set; }
        public Nullable<int> UserFieldOperation_UserId { get; set; }
        public Nullable<int> UserFieldOperation_FieldOperationId { get; set; }
        public Nullable<bool> UserFieldOperation_Active { get; set; }
    
        public virtual FieldOperation FieldOperation { get; set; }
        public virtual User User { get; set; }
    }
}
