//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int UserGroup_Id { get; set; }
        public Nullable<int> UserGroup_UserId { get; set; }
        public Nullable<int> UserGroup_GroupId { get; set; }
        public Nullable<System.DateTime> UserGroup_Status { get; set; }
        public Nullable<bool> UserGroup_Active { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
